- name: Apply ECK CRD manifest to the cluster.
  kubernetes.core.k8s:
    state: present
    src:  https://download.elastic.co/downloads/eck/{{ elastic_cloud_version }}/crds.yaml

- name: Create ECK operator.
  kubernetes.core.k8s:
    state: present
    src:  https://download.elastic.co/downloads/eck/{{ elastic_cloud_version }}/operator.yaml
