manetu_platform_chart_ref: oci://registry.gitlab.com/manetu/manetu-charts/manetu-platform
manetu_platform_mptest_chart_ref: oci://registry.gitlab.com/manetu/manetu-charts/mp-test
manetu_platform_version: 2.2.0-v2.2.0.b26.8435
manetu_chart_timeout: 15m
manetu_namespace: manetu-platform
manetu_registry_dns: registry.gitlab.com
manetu_registry_login: true
manetu_replicas_min: 3
manetu_kafka_partitions: 18
manetu_kafka_replicationfactor: 3
manetu_vault_domain: manetu.io
manetu_gateway_tls: true
manetu_gateway_tls_internal: true             # turn this off to manage the gateway-tls externally from the playbooks
manetu_gateway_tls_ca_duration: 87600h
manetu_gateway_tls_namespace: istio-system
manetu_gateway_tls_name: manetu-certificate   # the name of the TLS secret within {{manetu_gateway_tls_namespace}}  namespace
manetu_gateway_selector: ingress-gw             # the value of the "spec.selector.istio" in manetu-platform's Gateway
manetu_internal_dns: ingress                  # This will create 'ingress.manetu-platform'
manetu_peer_mtls_mode: STRICT                 # STRICT, PERMISSIVE, DISABLE
manetu_rollbar_enabled: true
manetu_rollbar_env:  ""                       # defaults to {{ Release.Namespace }}.{{ Release.Name }}

manetu_base_chart_values: {}  # Profile-based customization merged with {{ manetu_chart_values }}
manetu_chart_values: {}  # Allows customization

manetu_tolerations: "{{ default_tolerations | default([]) }}"
# - key: dedicated
#   operator: Equal
#   value: experimental
#   effect: NoSchedule

prometheus_monitor_labels: {}
monitoring_enabled: false
alerts_enabled: false
tracing_enabled: false
mp_test_enabled: false
