- name: "Set defaults"
  hosts: all
  tasks:
    - set_fact:
        manetu_namespace: "{{ manetu_namespace | default('manetu-platform') }}"

- name: "Deploy k3s"
  import_playbook: deploy-k3s.yml

- name: "Deploy Third-party"
  import_playbook: deploy-thirdparty.yml

- import_playbook: manetu.yml

- name: "Deploy Chaos Mesh"
  hosts: config_host
  roles:
    - chaos-mesh
