- name: "Set defaults"
  hosts: all
  tasks:
    - set_fact:
        manetu_namespace: "{{ manetu_namespace | default('manetu-platform') }}"

- name: "Deploy k8s infrastructure"
  hosts: config_host
  roles:
    - python
    - manetu-namespace # needs to be early so components may install configmaps/secrets
    - cert-manager
    - istio

- name: "Deploy Third-party"
  import_playbook: deploy-thirdparty.yml

- import_playbook: manetu.yml

- name: "Deploy Chaos Mesh"
  hosts: config_host
  roles:
    - chaos-mesh
