- name: Teardown Manetu
  gather_facts: false
  hosts: config_host
  roles:
    - python
  tasks:
    - name: Delete Manetu related namespaces
      kubernetes.core.k8s:
        state: absent
        kind: Namespace
        name: "{{ item }}"
      loop:
        - "{{ manetu_namespace | default('manetu-platform') }}"
        - "{{ temporal_namespace | default('manetu-temporal') }}"
        - "{{ yugabyte_namespace | default('manetu-yugabyte') }}"
        - "{{ kafka_namespace | default('manetu-kafka') }}"
        - "{{ cassandra_namespace | default('manetu-cassandra') }}"
        - "{{ minio_namespace | default('manetu-minio') }}"
        - "{{ vault_namespace | default('manetu-hashicorp') }}"
        - "{{ elasticsearch_namespace | default('manetu-elastic') }}"
        - "{{ qdrant_namespace | default('manetu-qdrant') }}"
