- name: Add extra labels to ServiceMonitor
  when: prometheus_monitor_labels
  kubernetes.core.k8s:
    state: patched
    namespace: "{{ minio_namespace }}"
    api_version: monitoring.coreos.com/v1
    kind: ServiceMonitor
    name: minio
    definition:
      metadata:
        labels: "{{ prometheus_monitor_labels | from_yaml }}"

- name: Add MinIO Alert Rules
  when: alerts_enabled
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: monitoring.coreos.com/v1
      kind: PrometheusRule
      metadata:
        labels:
          prometheus: minio
          role: alert-rules
        name: prometheus-minio-rules
        namespace: "{{ minio_namespace }}"
      spec: "{{ lookup('file', 'alert-rules.yaml') | from_yaml }}"
