yugabyte_tserver_replicas: 6
yugabyte_resources:
  master:
    requests:
      cpu: 2
      memory: 2Gi
    limits:
      cpu: 2
      memory: 2Gi
  tserver:
    requests:
      cpu: 14
      memory: 32Gi
    limits:
      cpu: 16
      memory: 32Gi

kafka_replicas: 6
kafka_resources:
  requests:
    memory: 8Gi
    cpu: 2
  limits:
    memory: 24Gi
    cpu: 4

zookeeper_replicas: 3
zookeeper_resources:
  requests:
    memory: 8Gi
    cpu: 2
  limits:
    memory: 8Gi
    cpu: 2

temporal_server_replicas: 5
temporal_frontend_replicas: 18
temporal_matching_replicas: 18
temporal_worker_replicas: 5

temporal_history_replicas: 18
temporal_history_resources: {}
temporal_history_shards: 3000

temporal_dynamic_config:
  matching.numTaskqueueReadPartitions:
  - value: 20
    constraints: {}
  matching.numTaskqueueWritePartitions:
  - value: 20
    constraints: {}

manetu_replicas_min: 6
manetu_base_chart_values: # merges with {{ manetu_chart_values }}
  mcp-attribute-service:
    cp:
      replicaCount: 6
  mcp-vault-service:
    cp:
      replicaCount: 6
  mcp-keycustodian-service-v2:
    cp:
      replicaCount: 6
  mcp-iam-service:
    cp:
      replicaCount: 6
