yugabyte_tserver_replicas: 6
yugabyte_resources:
  master:
    requests:
      cpu: 100m
      memory: 500Mi
    limits:
      cpu: 1
      memory: 1Gi
  tserver:
    requests:
      cpu: 8
      memory: 24Gi
    limits:
      cpu: 12
      memory: 32Gi

kafka_replicas: 6
kafka_resources:
  requests:
    memory: 6Gi
    cpu: 1000m
  limits:
    memory: 10Gi
    cpu: 2000m

zookeeper_replicas: 3
zookeeper_resources:
  requests:
    memory: 1Gi
    cpu: 100m
  limits:
    memory: 2Gi
    cpu: 1

temporal_frontend_replicas: 6
temporal_frontend_resources:
  requests:
    cpu: 550m
    memory: 250Mi
  limits:
    cpu: 2
    memory: 1Gi

temporal_matching_replicas: 6
temporal_matching_resources:
  requests:
    cpu: 350m
    memory: 250Mi
  limits:
    cpu: 2
    memory: 1Gi

temporal_history_shards: 2048 # Max 4096 per temporal
temporal_history_replicas: 6
temporal_history_resources:
  requests:
    cpu: 1200m
    memory: 3Gi
  limits:
    cpu: 4
    memory: 6Gi

# see https://docs.temporal.io/references/dynamic-configuration#service-level-rps-limits
temporal_dynamic_config:
  frontend.rps:
    - value: 4800                          # default: 2400
      constraints: {}
  frontend.namespaceRPS:
    - value: 4800                          # default: 2400
      constraints: {}
  frontend.persistenceMaxQPS:
    - value: 4000                          # default: 2000
      constraints: {}
  history.rps:
    - value: 6000                          # default: 3000
      constraints: {}
  history.persistenceMaxQPS:
    - value: 18000                         # default: 9000
      constraints: {}
  matching.rps:
    - value: 2400                          # default: 1200
      constraints: {}
  matching.persistenceMaxQPS:
    - value: 18000                         # default: 9000
      constraints: {}
  matching.numTaskqueueReadPartitions:
  - value: 10                              # default: 4
    constraints: {}
  matching.numTaskqueueWritePartitions:
  - value: 10                              # default: 4
    constraints: {}

istio_proxy_resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    cpu: 2000m
    memory: 1024Mi

manetu_replicas_min: 2
manetu_base_chart_values:  # merges with {{ manetu_chart_values }}
  mcp-graphql-service:
    replicaCount: 6
    istioProxyCpu: 100m
    resources:
      requests:
        cpu: 300m
        memory: 2Gi
      limits:
        memory: 4Gi
  mcp-attribute-service:
    gw:
      replicaCount: 6
      istioProxyCpu: 100m
      resources:
        requests:
          cpu: 200m
          memory: 2Gi
        limits:
          memory: 4Gi
    cp:
      replicaCount: 6
      istioProxyCpu: 100m
      resources:
        requests:
          cpu:  750m
          memory: 3Gi
        limits:
          memory: 5Gi
      temporal:
        worker:
          maxConcurrentActivityTaskPollers: 100 # default 5
          maxConcurrentWorkflowTaskPollers: 100 # default 2
          # maxConcurrentActivityExecutionSize: 200 # default
          maxConcurrentLocalActivityExecutionSize: 1000
          # maxConcurrentWorkflowTaskExecutionSize: 200 # default
          # workflowCacheSize: 600 # default
          maxWorkflowThreadCount: 2200 # sum of all above
  mcp-vault-service:
    gw:
      istioProxyCpu: 100m
      resources:
        requests:
          cpu: 100m
          memory: 2Gi
        limits:
          memory: 4Gi
    cp:
      replicaCount: 6
      istioProxyCpu: 100m
      resources:
        requests:
          cpu: 400m
          memory: 2Gi
        limits:
          memory: 4Gi
      temporal:
        worker:
          maxConcurrentActivityTaskPollers: 100
          maxConcurrentWorkflowTaskPollers: 100
          maxConcurrentActivityExecutionSize: 500
          # maxConcurrentLocalActivityExecutionSize: 200
          # maxConcurrentWorkflowTaskExecutionSize: 200
          workflowCacheSize: 1000
          maxWorkflowThreadCount: 2200
  mcp-keycustodian-service-v2:
    gw:
      istioProxyCpu: 100m
      replicaCount: 6
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          memory: 4Gi
    cp:
      istioProxyCpu: 100m
      replicaCount: 6
      resources:
        requests:
          cpu: 200m
          memory: 1500Mi
        limits:
          memory: 4Gi
      temporal:
        worker:
          maxConcurrentActivityTaskPollers: 100
          maxConcurrentWorkflowTaskPollers: 100
          # maxConcurrentActivityExecutionSize: 200
          # maxConcurrentLocalActivityExecutionSize: 200
          # maxConcurrentWorkflowTaskExecutionSize: 200
          workflowCacheSize: 1000
          maxWorkflowThreadCount: 1800
  mcp-accesslog-service:
    gw:
      istioProxyCpu: 1m
      resources:
        requests:
          cpu: 5m # runs when not contended
  mcp-analytics-service:
    sp:
      istioProxyCpu: 1m
      resources:
        requests:
          cpu: 5m # runs when not contended
  mcp-iam-service:
    query:
      replicaCount: 6
      istioProxyCpu: 100m
      resources:
        requests:
          cpu: 200m
          memory: 500Mi
        limits:
          memory: 2Gi
    gw:
      resources:
        requests:
          cpu: 150m
          memory: 1Gi
        limits:
          memory: 4Gi
    cp:
      replicaCount: 6
      istioProxyCpu: 100m
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          memory: 4Gi
      temporal:
        worker:
          maxConcurrentActivityTaskPollers: 100
          maxConcurrentWorkflowTaskPollers: 100
          # maxConcurrentActivityExecutionSize: 200
          # maxConcurrentLocalActivityExecutionSize: 200
          # maxConcurrentWorkflowTaskExecutionSize: 200
          workflowCacheSize: 1000
