yugabyte_tserver_replicas: 6
yugabyte_resources:
  master:
    requests:
      cpu: 250m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  tserver:
    requests:
      cpu: 2
      memory: 24Gi
    limits:
      cpu: 8 
      memory: 16Gi

kafka_replicas: 6
kafka_resources:
  requests:
    memory: 8Gi
    cpu: 1
  limits:
    memory: 16Gi
    cpu: 3

zookeeper_replicas: 3
zookeeper_resources:
  requests:
    memory: 4Gi
    cpu: 250m
  limits:
    memory: 8Gi
    cpu: 2000m

cassandra_replicas: 6
cassandra_resources:
  requests:
    memory: 16Gi
    cpu: 5
  limits:
    memory: 16Gi
    cpu: 12 

temporal_frontend_replicas: 6
temporal_frontend_resources:
  requests:
    cpu: 250m
  limits:
    cpu: 2 

temporal_matching_replicas: 6
temporal_matching_resources:
  requests:
    cpu: 250m
  limits:
    cpu: 1 

temporal_history_shards: 2048
temporal_history_replicas: 6
temporal_history_resources:
  requests:
    cpu: 1
  limits:
    cpu: 4 

temporal_dynamic_config:
  matching.numTaskqueueReadPartitions:
  - value: 10
    constraints: {}
  matching.numTaskqueueWritePartitions:
  - value: 10
    constraints: {}

istio_proxy_resources:
  requests:
    cpu: 10m

manetu_replicas_min: 2
manetu_base_chart_values:  # merges with {{ manetu_chart_values }}
  mcp-graphql-service:
    replicaCount: 6
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        memory: 4Gi
  mcp-attribute-service:
    gw:
      replicaCount: 6
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          memory: 4Gi
    cp:
      replicaCount: 6
      resources:
        requests:
          cpu: 1
          memory: 2Gi
        limits:
          memory: 4Gi
      temporal:
        worker:
          maxConcurrentActivityTaskPollers: 100 # default 5
          maxConcurrentWorkflowTaskPollers: 100 # default 2
          # maxConcurrentActivityExecutionSize: 200 # default
          maxConcurrentLocalActivityExecutionSize: 1000
          # maxConcurrentWorkflowTaskExecutionSize: 200 # default
          # workflowCacheSize: 600 # default
          maxWorkflowThreadCount: 2200 # sum of all above
  mcp-vault-service:
    gw:
      resources:
        requests:
          cpu: 250m
          memory: 2Gi
        limits:
          memory: 4Gi
    cp:
      replicaCount: 6
      resources:
        requests:
          cpu: 500m
          memory: 2Gi
        limits:
          memory: 4Gi
      temporal:
        worker:
          maxConcurrentActivityTaskPollers: 100
          maxConcurrentWorkflowTaskPollers: 100
          maxConcurrentActivityExecutionSize: 500
          # maxConcurrentLocalActivityExecutionSize: 200
          # maxConcurrentWorkflowTaskExecutionSize: 200
          workflowCacheSize: 1000
          maxWorkflowThreadCount: 2200
  mcp-keycustodian-service-v2:
    gw:
      replicaCount: 6
      resources:
        requests:
          cpu: 250m
          memory: 2Gi
        limits:
          memory: 4Gi
    cp:
      replicaCount: 6
      resources:
        requests:
          cpu: 250m
          memory: 2Gi
        limits:
          memory: 4Gi
      temporal:
        worker:
          maxConcurrentActivityTaskPollers: 100
          maxConcurrentWorkflowTaskPollers: 100
          # maxConcurrentActivityExecutionSize: 200
          # maxConcurrentLocalActivityExecutionSize: 200
          # maxConcurrentWorkflowTaskExecutionSize: 200
          workflowCacheSize: 1000
          maxWorkflowThreadCount: 1800
  mcp-iam-service:
    gw:
      resources:
        requests:
          cpu: 250m
          memory: 2Gi
        limits:
          memory: 4Gi
    cp:
      replicaCount: 6
      resources:
        requests:
          cpu: 250m
          memory: 2Gi
        limits:
          memory: 4Gi
      temporal:
        worker:
          maxConcurrentActivityTaskPollers: 100
          maxConcurrentWorkflowTaskPollers: 100
          # maxConcurrentActivityExecutionSize: 200
          # maxConcurrentLocalActivityExecutionSize: 200
          # maxConcurrentWorkflowTaskExecutionSize: 200
          workflowCacheSize: 1000
