yugabyte_resources:
  master:
    requests:
      cpu: 1
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
  tserver:
    requests:
      cpu: 4
      memory: 24Gi
    limits:
      cpu: 12
      memory: 32Gi

kafka_replicas: 3
kafka_resources:
  requests:
    memory: 8Gi
    cpu: 2
  limits:
    memory: 16Gi
    cpu: 3

zookeeper_replicas: 3
zookeeper_resources:
  limits:
    memory: 4Gi
    cpu: 250m

cassandra_replicas: 3
cassandra_resources:
  requests:
    memory: 16Gi
    cpu: 10
  limits:
    memory: 32Gi
    cpu: 12

temporal_frontend_replicas: 3
temporal_frontend_resources:
  requests:
    cpu: 1

temporal_matching_replicas: 6
temporal_matching_resources:
  requests:
    cpu: 500m

temporal_history_replicas: 6
temporal_history_resources:
  requests:
    cpu: 1500m

temporal_dynamic_config:
  matching.numTaskqueueReadPartitions:
  - value: 10
    constraints: {}
  matching.numTaskqueueWritePartitions:
  - value: 10
    constraints: {}

manetu_replicas_min: 2
manetu_base_chart_values:  # merges with {{ manetu_chart_values }}
  mcp-graphql-service:
    resources:
      requests:
        cpu: 500m
  mcp-attribute-service:
    gw:
      resources:
        requests:
          cpu: 500m
    cp:
      resources:
        requests:
          memory: 2Gi
          cpu: 2
  mcp-vault-service:
    gw:
      resources:
        requests:
          cpu: 250m
    cp:
      resources:
        requests:
          memory: 1Gi
          cpu: 1
  mcp-keycustodian-service-v2:
    gw:
      resources:
        requests:
          cpu: 250m
    cp:
      resources:
        requests:
          memory: 1Gi
          cpu: 500m
  mcp-iam-service:
    gw:
      resources:
        requests:
          cpu: 250m
    cp:
      resources:
        requests:
          cpu: 500m
